"""Calibrate kappa = (mean visible dimming) / (first-harmonic modulation amplitude) for random spot layouts.

The page-3 correction needs the star's mean dimming, but a rotation light curve only reveals how the
brightness changes. kappa links the two under an explicit prior over spot layouts: 2-5 circular spots,
sin(latitude) uniform in +-0.9, longitude uniform, angular radius uniform 6-20 degrees, spin axis edge-on,
no faculae. Uses the same 161-pixel grid as the page, so browser and Python agree closely.
Writes site/js/calibration.js. Run from the repository root:
    PYTHONPATH=src python scripts/calibrate_kappa.py
"""

import json
from pathlib import Path

import numpy as np

from pandora_sim import (Feature, LimbDarkening, Orbit, PixelGrid, Star, StellarSpectra, blackbody,
                         simulate_transit)

WAVELENGTH = 0.6  # micron, the visible proxy band
PROT = 4.0
N_STARS, N_PHASE, SEED = 1000, 48, 20260930
PRESETS = {"M": (3500, 3100, 3600), "K": (4500, 3900, 4600)}
# Named layouts keep the planet's path (impact parameter IMPACT) clear of every spot, even at 1.25x size,
# so the page shows unocculted contamination only.
IMPACT, RP, SIZE_MAX = 0.2, 0.06, 1.25
LAYOUTS = {
    "clustered": [("spot", 38, -10, 14), ("spot", -35, 15, 10), ("spot", 52, 35, 12)],
    "spread": [("spot", 40, 0, 10), ("spot", -35, 90, 10), ("spot", 35, 180, 10), ("spot", -45, 270, 10)],
}
grid = PixelGrid(161)


def chord_clear(features):
    """True if no spot, scaled by SIZE_MAX, overlaps the planet's path y in [IMPACT - RP, IMPACT + RP]."""
    for _, lat, _, radius in features:
        lo, hi = np.sin(np.radians(max(lat - radius * SIZE_MAX, -90))), np.sin(np.radians(min(lat + radius * SIZE_MAX, 90)))
        if hi > IMPACT - RP - 0.04 and lo < IMPACT + RP + 0.04:
            return False
    return True


for _name, _f in LAYOUTS.items():
    assert chord_clear(_f), _name
wl = np.array([WAVELENGTH])
ld = LimbDarkening(np.array([0.65 + (0.2 - 0.65) * (WAVELENGTH - 0.45) / 1.2]),
                   np.array([0.25 + (0.1 - 0.25) * (WAVELENGTH - 0.45) / 1.2]))
phase = np.arange(N_PHASE) / N_PHASE
cos, sin = np.cos(2 * np.pi * phase), np.sin(2 * np.pi * phase)


def kappa(features, teffs):
    spectra = StellarSpectra(wl, *(blackbody(wl, t) for t in teffs))
    star = Star([Feature(*f) for f in features], 90.0, 0.0, PROT)
    sim = simulate_transit(star, spectra, Orbit(3.0, 14.0, 89.0, 100.0), 0.06, phase * PROT, ld, grid)
    v = sim.star_flux[:, 0]                  # relative to the immaculate star
    mean_dimming = 1.0 - v.mean()
    data = v / v.mean()                      # what an observer sees: normalised by the data's own mean
    amp = np.hypot(2 * np.mean(data * cos), 2 * np.mean(data * sin))
    return mean_dimming / amp


def random_layout(rng):
    return [("spot", float(np.degrees(np.arcsin(rng.uniform(-0.9, 0.9)))), float(rng.uniform(0, 360)),
             float(rng.uniform(6, 20))) for _ in range(rng.integers(2, 6))]


rng = np.random.default_rng(SEED)
out = {"wavelength_um": WAVELENGTH, "prot_days": PROT, "n_stars": N_STARS, "seed": SEED, "stars": {}}
layouts = [random_layout(rng) for _ in range(N_STARS)]
for key, teffs in PRESETS.items():
    ks = np.array([kappa(f, teffs) for f in layouts])
    p16, p50, p84 = np.percentile(ks, [16, 50, 84])
    out["stars"][key] = {"p16": round(p16, 3), "p50": round(p50, 3), "p84": round(p84, 3),
                         "named_layouts": {n: round(kappa(f, teffs), 3) for n, f in LAYOUTS.items()}}
    print(key, out["stars"][key])

# A three-spot layout with a clear path whose kappa is closest to the median for both stars: the "typical" example.
best = None
for f in layouts:
    if len(f) != 3 or not chord_clear(f):
        continue
    err = max(abs(kappa(f, t) / out["stars"][k]["p50"] - 1) for k, t in PRESETS.items())
    if best is None or err < best[0]:
        best = (err, f)
out["typical_layout"] = [dict(kind=k, lat=round(a, 1), lon=round(b, 1), radius=round(c, 1)) for k, a, b, c in best[1]]
out["typical_layout_kappa"] = {k: round(kappa([(f["kind"], f["lat"], f["lon"], f["radius"]) for f in out["typical_layout"]], t), 3)
                               for k, t in PRESETS.items()}
print("typical layout", out["typical_layout"], out["typical_layout_kappa"])

out["layouts"] = {
    "clustered": [dict(kind=k, lat=a, lon=b, radius=c) for k, a, b, c in LAYOUTS["clustered"]],
    "typical": out["typical_layout"],
    "spread": [dict(kind=k, lat=a, lon=b, radius=c) for k, a, b, c in LAYOUTS["spread"]],
}

js = Path("site/js/calibration.js")
js.write_text("/* Generated by scripts/calibrate_kappa.py. Do not edit by hand. */\n"
              "(typeof self !== \"undefined\" ? self : globalThis).PandoraCalibration = " + json.dumps(out, indent=2) + ";\n")
print("wrote", js)
