"""Regenerate validation/phase1_report.md and validation/phase1.png.

Run from the repository root: ``PYTHONPATH=src python scripts/run_validation.py``.
"""

from pathlib import Path

import batman
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from pandora_sim import (Feature, LimbDarkening, Orbit, PixelGrid, Star, StellarSpectra, blackbody,
                         epsilon, simulate_transit, water_haze_radius_ratio)

OUT = Path("validation")
PERIOD = 3.0


def batman_residuals(n_pix=1201):
    one = np.ones(1)
    spectra = StellarSpectra(np.array([1.0]), one, one, one)
    rows = []
    for rp, a, inc, u in [(0.05, 10, 89, (0.4, 0.25)), (0.10, 8, 87, (0.5, 0.2)), (0.15, 6, 86, (0.3, 0.3))]:
        arg = np.sqrt((1 + rp) ** 2 - (a * np.cos(np.radians(inc))) ** 2) / a / np.sin(np.radians(inc))
        dur = PERIOD / np.pi * np.arcsin(arg)
        t = np.linspace(-0.7 * dur, 0.7 * dur, 81)
        sim = simulate_transit(Star(), spectra, Orbit(PERIOD, a, inc), rp, t, LimbDarkening(*u), PixelGrid(n_pix))
        p = batman.TransitParams()
        p.t0, p.per, p.rp, p.a, p.inc, p.ecc, p.w, p.u, p.limb_dark = 0, PERIOD, rp, a, inc, 0, 90, list(u), "quadratic"
        ref = batman.TransitModel(p, t).light_curve(p)
        rows.append((rp, a, inc, u, t, sim.flux[:, 0] - ref, rp**2))
    return rows


def contamination_example():
    wl = np.linspace(0.45, 1.65, 120)
    spectra = StellarSpectra(wl, blackbody(wl, 4500.0), blackbody(wl, 3800.0), blackbody(wl, 4600.0))
    rp = water_haze_radius_ratio(wl, rp0=0.08)
    star = Star([Feature("spot", 55, 10, 20), Feature("spot", -50, 200, 15), Feature("faculae", -45, -40, 20)],
                prot_days=12.0)
    orbit = Orbit(PERIOD, 8.0, 90.0)
    grid = PixelGrid(601)
    ld = LimbDarkening(np.linspace(0.65, 0.25, wl.size), np.linspace(0.2, 0.1, wl.size))
    spotted = simulate_transit(star, spectra, orbit, rp, [0.0], ld, grid)
    clean = simulate_transit(Star(), spectra, orbit, rp, [0.0], ld, grid)
    eps = epsilon(spotted.coverage[0, 1], spotted.coverage[0, 2], spectra.spot, spectra.fac, spectra.phot)
    worst = np.max(np.abs(spotted.depth[0] / (clean.depth[0] * eps) - 1))
    return wl, rp, clean.depth[0], spotted.depth[0], eps, worst, spotted.coverage[0, 1:].mean(1)


def main():
    OUT.mkdir(exist_ok=True)
    rows = batman_residuals()
    wl, rp, true_depth, obs_depth, eps, worst, cov = contamination_example()

    fig, ax = plt.subplots(1, 2, figsize=(11, 4))
    for rp_, a, inc, u, t, res, depth in rows:
        ax[0].plot(t * 24, res * 1e6, label=f"Rp/Rs={rp_}, depth={depth * 1e6:.0f} ppm")
    ax[0].set(xlabel="hours from mid-transit", ylabel="model - batman (ppm)", title="No-spot light curve vs batman")
    ax[0].legend(fontsize=8)
    ax[1].plot(wl, true_depth * 1e6, label="true depth (no spots)")
    ax[1].plot(wl, obs_depth * 1e6, label="observed, unocculted spots")
    ax[1].set(xlabel="wavelength (um)", ylabel="transit depth (ppm)", title="TLSE bias (blackbody placeholder)")
    ax[1].legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(OUT / "phase1.png", dpi=130)

    lines = [
        "# Phase 1 validation report",
        "",
        "Generated by `scripts/run_validation.py`. Stellar spectra here are blackbody placeholders,",
        "so these checks validate the geometry and the algebra, not the realism of the spectra.",
        "",
        "## Transit vs batman (no spots, pixel grid 1201 x 1201)",
        "",
        "| Rp/Rs | a/Rs | inc (deg) | u1, u2 | depth (ppm) | max abs residual (ppm) | residual / depth |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for rp_, a, inc, u, t, res, depth in rows:
        m = np.max(np.abs(res))
        lines.append(f"| {rp_} | {a} | {inc} | {u[0]}, {u[1]} | {depth * 1e6:.0f} | {m * 1e6:.2f} | {m / depth:.1e} |")
    lines += [
        "",
        "## Unocculted limit vs analytic epsilon",
        "",
        f"Chromatic limb darkening, two spots and one facular region (one spot is on the far side), 120 wavelengths. Flux-weighted coverage",
        f"spot/faculae = {cov[0]:.3f}/{cov[1]:.3f}. Largest relative difference between the pixel-model depth and",
        f"true depth x epsilon: **{worst:.1e}**. Peak epsilon = {eps.max():.4f}.",
        "",
        "![validation](phase1.png)",
        "",
        "## Not yet validated",
        "",
        "- Realistic stellar atmosphere spectra. The conceptual version uses blackbodies; the grid interpolator is tested on a synthetic grid only.",
        "- Pandora response curves (the band edges are published, but the Python bands are top hats).",
        "- Any joint fit. The site uses a simplified visible-anchored correction instead; see the page 3 tests.",
        "",
    ]
    (OUT / "phase1_report.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
